### ISSUE TITLE
Uncaught SyntaxError: Unexpected token < profile3.html:110

### ISSUE THREAD

**Issue by kamijoutouma** [uzairfarooq/arrive#31]
arive.js & arive.min.js on line 16 

:| 

<!DOCTYPE html>

@uzairfarooq

**Comment by uzairfarooq** [comment]
@kamijoutouma everything is fine at my end. Maybe something specific in your case, can you share the code snippet where you're registering `arrive` events?

**Comment by kamijoutouma** [comment]
i figured out the problem

it wasn't the snippet

it was because i was trying to load ./arrive.min.js which was wrong since i was trying to load it from another domain. so it should have been extdomain/arrive.min.js

Sorry about that 

was me derping extremely hard for about 3 hours x.x

@uzairfarooq
