### ISSUE TITLE
IE11: Object doesn't support property or method 'arrive'

### ISSUE THREAD

**Issue by ppov** [uzairfarooq/arrive#43]
That's the problem I have in IE11.
arrive.min.js is included before script that uses arrive event, FF and Chrome is fine.

**Comment by uzairfarooq** [comment]
@ppov thanks for reporting. Will fix it soon.

**Comment by uzairfarooq** [comment]
@ppov I just checked all test cases on IE 11 and it seems to be working fine. Can you visit the url in IE 11 and see if passes all test cases https://uzairfarooq.github.io/arrive/tests/SpecRunner.html

Also, can you check that you're not in compatibility mode. http://stackoverflow.com/questions/20577007/filereader-and-json-objects-not-defined-in-ie11

**Comment by ppov** [comment]
@uzairfarooq thanks for your reply. Compability mode was the reason. Good luck with arrive.js!
