### ISSUE TITLE
Not able to get trigger from Iframe

### ISSUE THREAD

**Issue by 3gwebtrain** [uzairfarooq/arrive#53]
Here is my origional question, can you answer here: [http://stackoverflow.com/questions/39753836/how-to-use-arrive-js-to-find-an-element-arrived-inside-of-a-iframe](http://stackoverflow.com/questions/39753836/how-to-use-arrive-js-to-find-an-element-arrived-inside-of-a-iframe)

Thanks

**Comment by uzairfarooq** [comment]
Sorry for the delayed response. It's limitation of `arrive.js`. Will look into it when I have some time. It's already reported here #32 so closing this one.
