### ISSUE TITLE
Can the leave function optionally check if the target element is non-existent?

### ISSUE THREAD

**Issue by Mattwmaster58** [uzairfarooq/arrive#63]
It would be really nice (:

**Comment by uzairfarooq** [comment]
The `leave` can still work even if there's no target element because the `leave` takes a selector and an element with the selector can be added to DOM at any time in future.

Would make sense if we add support in `leave` to take an element as argument.

**Comment by Mattwmaster58** [comment]
Feel to free to reopen if this is a good idea, but I have no idea what I was asking for here.
