### ISSUE TITLE
Possible Human Error | 

### ISSUE THREAD

**Issue by ghost** [uzairfarooq/arrive#67]
Hello! So I am having the issue where even once the element appears it does not fire. I am not sure if it is my fault, but to my knowledge it is 100% fine. To make your life easier, it is currently on my site [test.mylitenup.net](https://test.mylitenup.net) | Use the username "s" which will allow you to see the Enroll Now button which should be firing the arrive but it doesn't and this is thrown to the console "Uncaught DOMException: Failed to execute 'matches' on 'Element'".

**Comment by LitenUpNet** [comment]
# Human Error

In the code I called arrive using a variable grabbing the object at creation.

You may delete this if you wish.
